apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    install.operator.istio.io/owning-resource: ""
    install.operator.istio.io/owning-resource-namespace: ""
    operator.istio.io/component: IstioOperator
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.5
  name: istiooperators.install.istio.io
spec:
  conversion:
    strategy: None
  group: install.istio.io
  names:
    kind: IstioOperator
    listKind: IstioOperatorList
    plural: istiooperators
    shortNames:
    - iop
    singular: istiooperator
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IstioOperator is the Schema for the istiooperators API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MemcachedSpec defines the desired state of Memcached
          properties:
            foo:
              description: Foo is an example field of Memcached. Edit Memcached_types.go to remove/update
              type: string
          type: object
        status:
          description: MemcachedStatus defines the observed state of Memcached
          type: object
      type: object
