apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "install.istio.io/v1alpha1",
          "kind": "IstioOperator",
          "metadata": {
            "name": "istio-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: istiooperator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IstioOperator is the Schema for the istiooperators API
      displayName: IstioOperator
      kind: IstioOperator
      name: istiooperators.install.istio.io
      version: v1alpha1
  description: IstioOperator
  displayName: IstioOperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - install.istio.io
          resources:
          - istiooperators
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - install.istio.io
          resources:
          - istiooperators/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: istio-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: istio-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: istio-operator
            spec:
              containers:
              - command:
                - operator
                - server
                env:
                - name: WATCH_NAMESPACE
                  value: istio-system
                - name: LEADER_ELECTION_NAMESPACE
                  value: istio-operator
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: istio-operator
                image: harbor-b.alauda.cn/aml/istio-operator:1.6.5
                imagePullPolicy: IfNotPresent
                name: istio-operator
                resources:
                  limits:
                    cpu: 200m
                    memory: 256Mi
                  requests:
                    cpu: 50m
                    memory: 128Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: alauda-istio-operator
    url: https://fy-service.domain
  maturity: alpha
  provider:
    name: yuanfang
  version: 1.6.5
